using System.ComponentModel.DataAnnotations;

namespace SchoolManagment.Models.DTOs.Fees
{
    /// <summary>
    /// A payment received at the counter.
    ///
    /// <c>PaymentStatus</c> is gone. It was client-supplied, so a caller could record a
    /// <c>Pending</c> payment that no endpoint could ever move to <c>Completed</c>, or write a
    /// <c>Refunded</c> row directly and skip the refund audit. Every payment recorded here is
    /// <c>Completed</c>; a refund goes through its own endpoint.
    ///
    /// The cashier (<c>FeePayments.PaidBy</c>) is not here either: it is the signed-in user,
    /// taken from the token. The old repository never sent it, and the procedure requires it.
    /// </summary>
    public class FeePaymentCreateDTO
    {
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Choose the fee being paid")]
        public int FeeId { get; set; }

        [Required]
        [Range(0.01, 999999.99, ErrorMessage = "Amount must be between 0.01 and 999999.99")]
        public decimal AmountPaid { get; set; }

        /// <summary>One of <c>Constants.PaymentMethod</c>. The column has no CHECK, so this is the only guard.</summary>
        [Required(ErrorMessage = "Payment method is required")]
        [AllowedValues("Cash", "Card", "UPI", "BankTransfer", "Cheque",
            ErrorMessage = "Payment method must be Cash, Card, UPI, BankTransfer or Cheque")]
        public string PaymentMethod { get; set; } = string.Empty;

        /// <summary>Cheque number, card slip, UPI reference. Optional for cash.</summary>
        [StringLength(100, ErrorMessage = "Transaction reference cannot exceed 100 characters")]
        public string? TransactionId { get; set; }

        [StringLength(255, ErrorMessage = "Remarks cannot exceed 255 characters")]
        public string? Remarks { get; set; }
    }

    /// <summary>What a recorded payment is known by. The receipt number is generated by the server.</summary>
    public class FeePaymentResponseDTO
    {
        public int PaymentId { get; set; }
        public string ReceiptNumber { get; set; } = string.Empty;
    }
}
